### ISSUE TITLE
Implement basic layout and Introduce router

### ISSUE THREAD

**Issue by hackerwins** [yorkie-team/yorkie-house#5]
**Description**:

Implement basic layout and Introduce page router.

- [ ] Add a sidebar to the left side of the screen
  - Pages: `/documents`, `/settings`
  - Let's add `/projects` page after implementing https://github.com/yorkie-team/yorkie/issues/310
- [ ] Move the page when the user clicks on an item in the sidebar

references:
- https://flowbite.com/docs/components/sidebar/
- https://reactrouter.com/docs/en/v6/getting-started/installation

**Why**:
- Users can separate and manage multiple resources on each page in the service.

**Comment by chacha912** [comment]
@hackerwins Could I try this issue?

**Comment by hackerwins** [comment]
Welcome, @chacha912. Sure. 👍
