### ISSUE TITLE
Remove error popup when users try to sign up or logout

### ISSUE THREAD

**Issue by gollumnima** [yorkie-team/yorkie-house#55]
**Description**:
When users try to sign up or log out in [yorkie house](https://house.yorkie.dev/), users get an error message from the popup.
But I'm not sure this repository is the right place to discuss this issue. 

<img width="921" alt="스크린샷 2022-09-08 오후 8 11 27" src="https://user-images.githubusercontent.com/48143796/189108090-ba721715-1049-47cc-bbf7-ac6ea3d70a77.png">

**Why**:
I think this error message is not suitable for upper cases and we need to separate different cases for authentication.

**Comment by hackerwins** [comment]
@gollumnima Thanks for the report.
It's probably an unintended popup. So I added a label as a bug.
